### ISSUE TITLE
Auto formatting with Black

### ISSUE THREAD

**Issue by matejc** [eficode/robotframework-oxygen#25]
When we have Github Actions PR merged, we might look into Black for automatic code formatting.

We might use something of a sort (not tested):

```yaml
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
      - uses: psf/black@stable
        with:
          options: "--verbose"
      - name: Commit black formatting results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Format Python code with psf/black push"
```
